# Generated by Django 4.2.6 on 2023-10-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='embed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(blank=True, to='posts.post'),
        ),
    ]
