# Generated by Django 4.2.6 on 2023-10-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_media_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='embed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='posts.post'),
        ),
    ]
