# Generated by Django 4.2.6 on 2023-11-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='embed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='posts.post'),
        ),
    ]
