# Generated by Django 4.2.6 on 2023-11-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0017_alter_mention_post"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.chat"
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("chat", "user_profile")},
            },
        ),
        migrations.RemoveField(
            model_name="chat",
            name="user_profiles",
            field=models.ManyToManyField(
                related_name="chats", to="user_profile.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="user_profiles",
            field=models.ManyToManyField(
                related_name="chats",
                through="chat.ChatUser",
                to="user_profile.userprofile",
            ),
        ),
    ]
