# Generated by Django 4.2.6 on 2023-11-14 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0017_alter_mention_post"),
        ("chat", "0002_chatuser_alter_chat_user_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="first_user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="user_profile.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chat",
            name="second_user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together={("first_user_profile", "second_user_profile")},
        ),
        migrations.RemoveField(
            model_name="chat",
            name="user_profiles",
        ),
        migrations.DeleteModel(
            name="ChatUser",
        ),
    ]
