# Generated by Django 4.2.6 on 2023-11-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_first_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-creation']},
        ),
    ]
