# Generated by Django 4.2.6 on 2023-11-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['creation']},
        ),
    ]
