# Generated by Django 4.2.6 on 2023-12-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
    ]
