# Generated by Django 4.2.6 on 2023-10-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
