# Generated by Django 4.2.6 on 2023-10-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_avatar_userprofile_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(null=True, to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(null=True, to='user_profile.userprofile'),
        ),
    ]
