# Generated by Django 4.2.6 on 2023-10-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_media_post'),
        ('user_profile', '0009_remove_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_posts',
            field=models.ManyToManyField(related_name='likes', to='posts.post'),
        ),
    ]
