# Generated by Django 4.2.6 on 2023-10-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_rename_following_user_id_userfollowing_following_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='following_user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user_profile.userprofile'),
        ),
    ]
