# Generated by Django 4.2.6 on 2023-11-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_alter_userfollowing_following_user_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_mentions', to='user_profile.userprofile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='user_profile.userprofile')),
            ],
        ),
    ]
