# Generated by Django 4.2.6 on 2023-11-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_mentions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentions',
            new_name='Mention',
        ),
    ]
