# Generated by Django 4.2.6 on 2023-11-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_rename_mentions_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='end_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mention',
            name='start_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
