# Generated by Django 4.2.6 on 2023-11-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_embed'),
        ('user_profile', '0016_mention_end_index_mention_start_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_mentions', to='posts.post'),
        ),
    ]
