# Generated by Django 4.2.6 on 2023-12-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_remove_notification_issuer_notification_issuer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
