# Generated by Django 4.2.6 on 2023-12-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_alter_media_file"),
        ("user_profile", "0020_rename_reciever_notification_receiver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="issuer_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="issuer_type",
        ),
        migrations.AddField(
            model_name="notification",
            name="issuer",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                default=11, on_delete=django.db.models.deletion.CASCADE, to="posts.post"
            ),
            preserve_default=False,
        ),
    ]
