# Generated by Django 4.2.6 on 2023-12-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_remove_notification_issuer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
